In [1]:
import tensorflow as tf

In [5]:
print(tf.VERSION)

1.3.0


In [7]:
hello=tf.constant("Nikhil")
world=tf.constant("Goyal")
type(hello)
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


hello is not a string variable now.Now it is tensorflow object

In [10]:
with tf.Session() as session:
    result=session.run(hello+'::'+world)    

In [11]:
print(result)

b'Nikhil::Goyal'


In [17]:
a=tf.constant(100)
b=tf.constant(200)
print(a)

Tensor("add_5:0", shape=(), dtype=int32)


here a is constant with type int32

In [19]:
with tf.Session() as session:
    result2=session.run(a+b)  

In [20]:
print(result)

300


In [28]:
con=tf.constant(30)
fil3= tf.fill((3,3),10)
zeroes=tf.zeros((2,2))
myone=tf.ones((4,4))
random=tf.random_normal((4,4),mean=0,stddev=1.0)

In [29]:
my_constant=[con,fil3,zeroes,myone,random]

In [30]:
session=tf.InteractiveSession()

In [33]:
for ops in my_constant:
    print(session.run(ops))
    print("\n")

30


[[10 10 10]
 [10 10 10]
 [10 10 10]]


[[ 0.  0.]
 [ 0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.87519997 -0.51784974  1.00517964 -2.08141637]
 [-1.07569742 -0.28428853 -0.45011777  1.21002364]
 [-0.78687102  0.07720553 -0.72633415  0.42783451]
 [ 1.14623666  0.46128789  0.04829095  1.6388427 ]]




In [36]:
a=tf.constant([[1,2],[3,4]])
a.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_20:0' shape=(2, 2) dtype=int32>>

In [39]:
b= tf.constant([[1],[2]])
b.get_shape

<bound method Tensor.get_shape of <tf.Tensor 'Const_22:0' shape=(2, 1) dtype=int32>>

In [40]:
result=tf.matmul(a,b)

In [41]:
session.run(result)

array([[ 5],
       [11]])

In [42]:
# The above code is an example of multiplication of arraays in tensorflow