In [1]:
import tensorflow as tf

In [5]:
print(tf.VERSION)

1.3.0


In [7]:
hello=tf.constant("Nikhil")
world=tf.constant("Goyal")
type(hello)
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


hello is not a string variable now.Now it is tensorflow object

In [10]:
with tf.Session() as session:
    result=session.run(hello+'::'+world)    

In [11]:
print(result)

b'Nikhil::Goyal'


In [17]:
a=tf.constant(100)
b=tf.constant(200)
print(a)

Tensor("add_5:0", shape=(), dtype=int32)


here a is constant with type int32

In [19]:
with tf.Session() as session:
    result2=session.run(a+b)  

In [20]:
print(result)

300


In [28]:
con=tf.constant(30)
fil3= tf.fill((3,3),10)
zeroes=tf.zeros((2,2))
myone=tf.ones((4,4))
random=tf.random_normal((4,4),mean=0,stddev=1.0)

In [29]:
my_constant=[con,fil3,zeroes,myone,random]

In [30]:
session=tf.InteractiveSession()

In [31]:
for ops in my_constant:
    print(session.run(ops))

30
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[-0.83568788  0.29208723 -0.19023316  0.22286493]
 [ 0.20256713 -3.00012255  0.02754926 -0.37865573]
 [ 0.06090693 -0.39712474  0.51877463 -0.42876679]
 [ 1.03472698  0.14685486 -0.64521956 -0.67330509]]
